// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cinematica.API.Models.Database
{
    public class Like
    {
        public long LikeId { get; set; }
        public string UserId { get; set; }
        public long? PostId { get; set; }
        public long? ReplyId { get; set; }

        public virtual Post? Post { get; set; }
        public virtual Reply? Reply { get; set; }
        public virtual User User { get; set; }
    }
}