// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cinematica.API.Models.Database
{
    public partial class MovieSelection
    {
        public long PostId { get; set; }
        public int MovieId { get; set; }

        public virtual DBMovie Movie { get; set; }
        public virtual Post Post { get; set; }
    }
}