// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cinematica.API.Models.Database
{
    public partial class Studio
    {
        public int StudioId { get; set; }
        public string StudioName { get; set; }
    }
}